# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\BHJ\NSCC\PROG1700-w0411909\assingment\FinalProject\CountriesOfTheWorld.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(998, 805)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.listWidget_countrylist = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget_countrylist.setGeometry(QtCore.QRect(15, 70, 401, 671))
        self.listWidget_countrylist.setObjectName("listWidget_countrylist")
        self.Label_list = QtWidgets.QLabel(self.centralwidget)
        self.Label_list.setGeometry(QtCore.QRect(20, 30, 351, 20))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.Label_list.setFont(font)
        self.Label_list.setObjectName("Label_list")
        self.label_Countryname = QtWidgets.QLabel(self.centralwidget)
        self.label_Countryname.setGeometry(QtCore.QRect(431, 70, 261, 41))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_Countryname.setFont(font)
        self.label_Countryname.setObjectName("label_Countryname")
        self.label_Population = QtWidgets.QLabel(self.centralwidget)
        self.label_Population.setGeometry(QtCore.QRect(430, 330, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(13)
        self.label_Population.setFont(font)
        self.label_Population.setObjectName("label_Population")
        self.pushButton_update = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_update.setGeometry(QtCore.QRect(680, 390, 231, 41))
        self.pushButton_update.setObjectName("pushButton_update")
        self.label_Area = QtWidgets.QLabel(self.centralwidget)
        self.label_Area.setGeometry(QtCore.QRect(430, 490, 131, 31))
        self.label_Area.setObjectName("label_Area")
        self.textEdit_Population = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_Population.setGeometry(QtCore.QRect(550, 330, 361, 41))
        self.textEdit_Population.setDocumentTitle("")
        self.textEdit_Population.setObjectName("textEdit_Population")
        self.comboBox_squremeter = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_squremeter.setGeometry(QtCore.QRect(560, 490, 131, 31))
        self.comboBox_squremeter.setObjectName("comboBox_squremeter")
        self.comboBox_squremeter.addItem("")
        self.comboBox_squremeter.addItem("")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(440, 560, 461, 101))
        self.groupBox.setObjectName("groupBox")
        self.radioButton_sm = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_sm.setGeometry(QtCore.QRect(30, 30, 201, 28))
        self.radioButton_sm.setObjectName("radioButton_sm")
        self.radioButton_km = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_km.setGeometry(QtCore.QRect(30, 60, 151, 28))
        self.radioButton_km.setObjectName("radioButton_km")
        self.label_density_output = QtWidgets.QLabel(self.groupBox)
        self.label_density_output.setGeometry(QtCore.QRect(320, 40, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_density_output.setFont(font)
        self.label_density_output.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_density_output.setText("")
        self.label_density_output.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_density_output.setObjectName("label_density_output")
        self.label_percent = QtWidgets.QLabel(self.centralwidget)
        self.label_percent.setGeometry(QtCore.QRect(430, 680, 381, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_percent.setFont(font)
        self.label_percent.setObjectName("label_percent")
        self.label_percent_output = QtWidgets.QLabel(self.centralwidget)
        self.label_percent_output.setGeometry(QtCore.QRect(750, 690, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_percent_output.setFont(font)
        self.label_percent_output.setText("")
        self.label_percent_output.setObjectName("label_percent_output")
        self.label_area_output = QtWidgets.QLabel(self.centralwidget)
        self.label_area_output.setGeometry(QtCore.QRect(753, 490, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_area_output.setFont(font)
        self.label_area_output.setText("")
        self.label_area_output.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_area_output.setObjectName("label_area_output")
        self.label_Flag = QtWidgets.QLabel(self.centralwidget)
        self.label_Flag.setGeometry(QtCore.QRect(570, 130, 241, 151))
        self.label_Flag.setText("")
        self.label_Flag.setObjectName("label_Flag")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 998, 26))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.actionLoad_Countries = QtWidgets.QAction(MainWindow)
        self.actionLoad_Countries.setObjectName("actionLoad_Countries")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionExit_2 = QtWidgets.QAction(MainWindow)
        self.actionExit_2.setObjectName("actionExit_2")
        self.menuFile.addAction(self.actionLoad_Countries)
        self.menuFile.addAction(self.actionExit)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit_2)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Label_list.setText(_translate("MainWindow", "Choose a Countries from the list:"))
        self.label_Countryname.setText(_translate("MainWindow", "Country Name"))
        self.label_Population.setText(_translate("MainWindow", "Population:"))
        self.pushButton_update.setText(_translate("MainWindow", "Update Population"))
        self.label_Area.setText(_translate("MainWindow", "Total Area In"))
        self.textEdit_Population.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Calibri\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.comboBox_squremeter.setItemText(0, _translate("MainWindow", "Sq. KM"))
        self.comboBox_squremeter.setItemText(1, _translate("MainWindow", "Sq. Miles"))
        self.groupBox.setTitle(_translate("MainWindow", "Population Density"))
        self.radioButton_sm.setText(_translate("MainWindow", "Per Squre Mile"))
        self.radioButton_km.setText(_translate("MainWindow", "Per Squre KM"))
        self.label_percent.setText(_translate("MainWindow", "Percentage of World Population:"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionLoad_Countries.setText(_translate("MainWindow", "Load Countries"))
        self.actionExit.setText(_translate("MainWindow", "Save To File"))
        self.actionExit_2.setText(_translate("MainWindow", "Exit"))

